# Code Generated by Sidekick is for learning and experimentation purposes only.
{{- define "wellsfargo.name" -}}
wellsfargo
{{- end -}}

{{- define "wellsfargo-task.name" -}}
wellsfargo-task
{{- end -}}

{{- define "wellsfargo.fullname" -}}
{{ .Release.Name }}-wellsfargo
{{- end -}}

{{- define "wellsfargo-task.fullname" -}}
{{ .Release.Name }}-wellsfargo-task
{{- end -}}

{{- define "wellsfargo.labels" -}}
app.kubernetes.io/name: {{ include "wellsfargo.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{- define "wellsfargo.selectorLabels" -}}
app.kubernetes.io/name: {{ include "wellsfargo.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{/* _helpers.tpl */}}

{{- define "yourchart.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "yourchart.name" -}}
{{- .Chart.Name -}}
{{- end -}}
