apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wellsfargo.fullname" . }}-db-init
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-init
        image: {{ .Values.initContainer.image }}
        env:
          - name: DB_DEPLOYMENT
            value: {{ .Values.initContainer.env.DB_DEPLOYMENT | quote }}
          - name: INITIAL_DEPLOYMENT
            value: {{ .Values.initContainer.env.INITIAL_DEPLOYMENT | quote }}
          - name: DB_HOST
            value: {{ .Values.initContainer.env.DB_HOST | quote }}
          - name: DB_PORT
            value: {{ .Values.initContainer.env.DB_PORT | quote }}
          - name: DB_USER
            value: {{ .Values.initContainer.env.DB_USER | quote }}
          - name: DB_PASS
            value: {{ .Values.initContainer.env.DB_PASS | quote }}
          - name: DB_NAME
            value: {{ .Values.initContainer.env.DB_NAME | quote }}
          - name: DB_WAIT_TIME
            value: "5"
        command: ["/scripts/db.sh"]  # Use DB-only script that doesn't start Tomcat