# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "wellsfargo.fullname" . }}-config-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: {{ .Release.Name }}-iiq-config-nfs
#   resources:
#     requests:
#       storage: {{ .Values.storage.size | default "1Gi" }}