apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wellsfargo.fullname" . }}-scaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "wellsfargo.fullname" . }}-scaler
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wellsfargo.fullname" . }}-scaler
subjects:
- kind: ServiceAccount
  name: {{ include "wellsfargo.fullname" . }}-scaler
roleRef:
  kind: Role
  name: {{ include "wellsfargo.fullname" . }}-scaler
  apiGroup: rbac.authorization.k8s.io