apiVersion: v1
kind: Service
metadata:
  name: {{ include "wellsfargo.fullname" . }}
  labels:
    {{- include "wellsfargo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30080
  selector:
    {{- include "wellsfargo.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
